name: Object Detection Inference Visualized
description: A blog-style application to visualize object detection workflow
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-03-18"
api_version: 1

tasks:
  - type: create_job
    name: Install Dependencies
    entity_label: install_dependencies
    script: cml/install_dependencies.py
    arguments: None
    cpu: 2
    memory: 4
    short_summary: Create job to install project dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3

  - type: run_job
    entity_label: install_dependencies
    short_summary: Running install dependencies job.
    long_summary: Running install dependencies job.

  - type: start_application
    name: Launch Streamlit Application
    subdomain: streamlit
    script: cml/launch_app.py
    short_summary: Starting Streamlit application
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3
